//! Bootstrap helpers for `wayfinder-router init` / `doctor`.
//!
//! Pure scaffolding to get started fast: render a starter `wayfinder-router.toml`
//! from a preset, a matching `.env.example` (env-var *names* only, never a secret),
//! and report whether each model's key resolves from the environment.
//!
//! Wayfinder reads keys from the environment at request time and never stores them
//! (WF-ADR-0004); these helpers only ever name the variables.

use std::collections::{BTreeMap, BTreeSet};
use std::io::Read;
use std::process::{Command, Stdio};
use std::sync::LazyLock;
use std::time::{Duration, Instant};

use crate::GatewayModel;

/// How long to wait on a key-resolution command (WF-DESIGN-0006), generous enough
/// for an interactive vault unlock (e.g. a 1Password biometric prompt).
const KEY_CMD_TIMEOUT: Duration = Duration::from_secs(30);

/// A named starter configuration: the toml to write and the env vars it needs.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Preset {
    pub name: &'static str,
    pub summary: &'static str,
    pub config_toml: &'static str,
    pub env_vars: &'static [&'static str],
}

// The hybrid preset: a keyless local Ollama arm and an Anthropic cloud arm. It best
// shows the local-vs-cloud value and the keyless path; tune or swap endpoints freely.
const HYBRID_TOML: &str = r#"# wayfinder-router.toml — generated by `wayfinder-router init` (preset: hybrid).
#
# Wayfinder never stores secrets: a model names an env var (api_key_env) and the key
# is read from your environment at request time (WF-ADR-0004). Edit this file freely;
# re-run `wayfinder-router doctor` to check your setup.

[routing]
# Structural cut: prompts scoring below this stay on the local arm; at or above it
# they escalate to cloud. Tune with `wayfinder-router calibrate`, or /threshold in chat.
threshold = 0.08

# Local arm — Ollama (OpenAI-compatible, keyless). Start it with `ollama serve`,
# then pull the model: `ollama pull llama3.1`.
[gateway.models.local]
base_url = "http://localhost:11434/v1"
model = "llama3.1"
cost_per_1k = 0.0   # local inference is free; used for the chat's savings estimate

# Cloud arm — Anthropic. The key is read from $ANTHROPIC_API_KEY at request time;
# it is never written here. `export ANTHROPIC_API_KEY=...` before running.
[gateway.models.cloud]
base_url = "https://api.anthropic.com/v1"
model = "claude-sonnet-4-6"
api_key_env = "ANTHROPIC_API_KEY"
# Prefer not to `export` a raw key? Fill it from your secret store at startup instead
# (held in memory only, never written to disk). `wayfinder-router doctor` suggests a line:
# api_key_cmd = "op read op://Private/Anthropic/credential"   # 1Password / Keychain / pass / …
cost_per_1k = 0.009   # rough $/1k tokens (blended) — edit for your pricing

# Prefer Google Gemini for the cloud arm? Gemini speaks OpenAI's /chat/completions at
# its compat base_url, so it drops straight in — swap the [gateway.models.cloud] block
# above for the one below (key read from $GEMINI_API_KEY at request time, never stored):
# [gateway.models.cloud]
# base_url = "https://generativelanguage.googleapis.com/v1beta/openai"
# model = "gemini-2.5-flash"
# api_key_env = "GEMINI_API_KEY"
# cost_per_1k = 0.0003   # rough $/1k tokens (blended) — edit for your pricing
"#;

// The openai preset: one provider, two cost tiers (a small fast model and a large
// capable one). Both arms read the same OPENAI_API_KEY. Tier names are cost labels,
// not locations — there is no on-device arm here.
const OPENAI_TOML: &str = r#"# wayfinder-router.toml — generated by `wayfinder-router init --preset openai`.
#
# Wayfinder never stores secrets: a model names an env var (api_key_env) and the key
# is read from your environment at request time (WF-ADR-0004). Edit this file freely;
# re-run `wayfinder-router doctor` to check your setup.

# Two cost tiers from one provider: prompts scoring below the cut use the small model;
# at or above it they escalate to the large one. Tune cuts with `wayfinder-router calibrate`.
[[routing.tiers]]
min_score = 0.0
model = "small"

[[routing.tiers]]
min_score = 0.08
model = "large"

# Small (cheap) arm.
[gateway.models.small]
base_url = "https://api.openai.com/v1"
model = "gpt-4o-mini"
api_key_env = "OPENAI_API_KEY"
cost_per_1k = 0.0004   # rough $/1k tokens (blended) — edit for your pricing

# Large (capable) arm — same key, read from the environment at request time.
[gateway.models.large]
base_url = "https://api.openai.com/v1"
model = "gpt-4o"
api_key_env = "OPENAI_API_KEY"
cost_per_1k = 0.0075   # rough $/1k tokens (blended) — edit for your pricing
"#;

// The gemini preset: two cost tiers from Google Gemini via its OpenAI-compatible endpoint
// (Flash → Pro). Both arms read the same GEMINI_API_KEY. Like `openai`, tier names are
// cost labels, not locations — there is no on-device arm here.
const GEMINI_TOML: &str = r#"# wayfinder-router.toml — generated by `wayfinder-router init --preset gemini`.
#
# Wayfinder never stores secrets: a model names an env var (api_key_env) and the key
# is read from your environment at request time (WF-ADR-0004). Edit this file freely;
# re-run `wayfinder-router doctor` to check your setup.

# Two cost tiers from Google Gemini: prompts scoring below the cut use Flash; at or above
# it they escalate to Pro. Tune cuts with `wayfinder-router calibrate`.
[[routing.tiers]]
min_score = 0.0
model = "flash"

[[routing.tiers]]
min_score = 0.08
model = "pro"

# Flash (cheap, fast) arm. Gemini speaks OpenAI's /chat/completions at this base_url; the
# key is read from $GEMINI_API_KEY at request time and is never written here.
[gateway.models.flash]
base_url = "https://generativelanguage.googleapis.com/v1beta/openai"
model = "gemini-2.5-flash"
api_key_env = "GEMINI_API_KEY"
cost_per_1k = 0.0003   # rough $/1k tokens (blended) — edit for your pricing

# Pro (capable) arm — same key, read from the environment at request time.
[gateway.models.pro]
base_url = "https://generativelanguage.googleapis.com/v1beta/openai"
model = "gemini-2.5-pro"
api_key_env = "GEMINI_API_KEY"
cost_per_1k = 0.005   # rough $/1k tokens (blended) — edit for your pricing
"#;

/// The preset chosen when none is named.
pub const DEFAULT_PRESET: &str = "hybrid";

/// The named starter configurations, keyed by name.
pub static PRESETS: LazyLock<BTreeMap<&'static str, Preset>> = LazyLock::new(|| {
    BTreeMap::from([
        (
            "hybrid",
            Preset {
                name: "hybrid",
                summary: "keyless local Ollama → Anthropic cloud",
                config_toml: HYBRID_TOML,
                env_vars: &["ANTHROPIC_API_KEY"],
            },
        ),
        (
            "openai",
            Preset {
                name: "openai",
                summary: "OpenAI two-tier (gpt-4o-mini → gpt-4o)",
                config_toml: OPENAI_TOML,
                env_vars: &["OPENAI_API_KEY"],
            },
        ),
        (
            "gemini",
            Preset {
                name: "gemini",
                summary: "Gemini two-tier (gemini-2.5-flash → gemini-2.5-pro)",
                config_toml: GEMINI_TOML,
                env_vars: &["GEMINI_API_KEY"],
            },
        ),
    ])
});

/// The `wayfinder-router.toml` scaffold for `preset` (loads back unchanged).
pub fn render_config(preset: &Preset) -> String {
    preset.config_toml.to_string()
}

/// A `.env.example` with the preset's env-var *names* only — never a secret.
pub fn render_env_example(preset: &Preset) -> String {
    let mut lines = vec![
        "# Wayfinder model keys — export these in your shell (e.g. via direnv or dotenv)."
            .to_string(),
        "# Wayfinder reads them at request time and never writes secrets to disk.".to_string(),
        "# Leave a value blank to rely on the keyless local arm only.".to_string(),
        String::new(),
    ];
    for name in preset.env_vars {
        lines.push(format!("{name}="));
    }
    lines.join("\n") + "\n"
}

/// Whether one model's key resolves: the env-var name and whether it is set.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct KeyStatus {
    /// The gateway model name (the routing target).
    pub name: String,
    /// The upstream model id.
    pub model: String,
    pub base_url: String,
    /// The env var holding the key, or `None` for a keyless arm.
    pub env_var: Option<String>,
    /// Keyless, or the named var is set (non-empty).
    pub ok: bool,
    /// Command that fills `env_var` when unset (WF-DESIGN-0006), if any.
    pub cmd: Option<String>,
}

/// Report each model's key readiness — the same rule the gateway uses (key from env).
///
/// A pure read of the environment; it never runs an `api_key_cmd`. Call
/// [`resolve_keys`] first if you want command-filled keys reflected here.
pub fn key_status(models: &BTreeMap<String, GatewayModel>) -> Vec<KeyStatus> {
    key_status_with(models, |name| std::env::var(name).ok())
}

fn key_status_with(
    models: &BTreeMap<String, GatewayModel>,
    lookup: impl Fn(&str) -> Option<String>,
) -> Vec<KeyStatus> {
    models
        .iter()
        .map(|(name, model)| {
            let env_var = model.api_key_env.clone();
            let ok = match &env_var {
                None => true,
                Some(var) => lookup(var).is_some_and(|value| !value.is_empty()),
            };
            KeyStatus {
                name: name.clone(),
                model: model.model.clone(),
                base_url: model.base_url.clone(),
                env_var,
                ok,
                cmd: model.api_key_cmd.clone(),
            }
        })
        .collect()
}

/// Distinct env-var names that are named but unset (sorted, deduped).
pub fn missing_keys(statuses: &[KeyStatus]) -> Vec<String> {
    statuses
        .iter()
        .filter(|status| !status.ok)
        .filter_map(|status| status.env_var.clone())
        .collect::<BTreeSet<_>>()
        .into_iter()
        .collect()
}

/// Fill each model's `api_key_env` from its `api_key_cmd` when the var is unset.
///
/// Runs the user's command (e.g. `op read op://Private/Anthropic/key`) and loads the
/// result into the process environment **in memory only** — the secret is never written
/// to config or disk. An env var that is already set always wins (CI, an explicit
/// `export`), so the command runs only when needed and is never required.
///
/// Returns a `{model_name: error_message}` map for commands that failed (empty when
/// everything resolved or had nothing to do). Errors carry the *command*, never a key.
pub fn resolve_keys(models: &BTreeMap<String, GatewayModel>) -> BTreeMap<String, String> {
    let mut errors = BTreeMap::new();
    for (name, model) in models {
        // Keyless, no command, or the key is already present.
        let (Some(cmd), Some(var)) = (&model.api_key_cmd, &model.api_key_env) else {
            continue;
        };
        if std::env::var(var).is_ok_and(|value| !value.is_empty()) {
            continue;
        }
        match run_key_cmd(cmd) {
            Ok(value) if value.is_empty() => {
                errors.insert(name.clone(), format!("command produced no output: {cmd}"));
            }
            Ok(value) => {
                // SAFETY: edition 2021; in-process only, never persisted to disk.
                std::env::set_var(var, value);
            }
            Err(message) => {
                errors.insert(name.clone(), message);
            }
        }
    }
    errors
}

/// Run `cmd` in a shell and return its stdout (the key), trimmed.
///
/// Uses `sh -c` so users can write the same line their secret tool documents
/// (`op read op://...`, `security find-generic-password -w ...`). The command comes
/// from the user's own config, so it runs with their privileges — the same trust as a
/// line they would type to `export` the key themselves. stderr is inherited so an
/// interactive unlock prompt still reaches the terminal; only stdout (the secret) is
/// captured, and it is never logged.
fn run_key_cmd(cmd: &str) -> Result<String, String> {
    let mut child = Command::new("sh")
        .arg("-c")
        .arg(cmd)
        .stdout(Stdio::piped())
        .spawn()
        .map_err(|err| format!("could not run command: {err}"))?;
    let started = Instant::now();
    let status = loop {
        match child.try_wait() {
            Ok(Some(status)) => break status,
            Ok(None) => {
                if started.elapsed() >= KEY_CMD_TIMEOUT {
                    let _ = child.kill();
                    let _ = child.wait();
                    return Err(format!(
                        "timed out after {}s: {cmd}",
                        KEY_CMD_TIMEOUT.as_secs()
                    ));
                }
                std::thread::sleep(Duration::from_millis(50));
            }
            Err(err) => return Err(format!("could not run command: {err}")),
        }
    };
    let mut out = String::new();
    if let Some(mut stdout) = child.stdout.take() {
        stdout
            .read_to_string(&mut out)
            .map_err(|err| format!("could not read command output: {err}"))?;
    }
    if !status.success() {
        let code = status
            .code()
            .map_or_else(|| "signal".to_string(), |code| code.to_string());
        return Err(format!("command exited {code}: {cmd}"));
    }
    Ok(out.trim().to_string())
}

// Secret tools we can recommend an `api_key_cmd` for, in preference order. Each maps a
// detected executable to a fill-in-the-blank command the user can paste and adjust. The
// resolver runs *any* command; this list only drives the friendly suggestions.
//
// NOTE: single-quote any inner literals so the line stays a valid double-quoted TOML
// value (`api_key_cmd = "<cmd>"`) when copy-pasted — guarded by a test.
const KEY_HELPERS: &[(&str, &str, &str)] = &[
    ("op", "1Password", "op read 'op://Private/{var}/credential'"),
    (
        "security",
        "macOS Keychain",
        "security find-generic-password -w -s '{var}'",
    ),
    (
        "secret-tool",
        "Linux Secret Service",
        "secret-tool lookup service '{var}'",
    ),
    ("pass", "pass", "pass show {var}"),
    ("gopass", "gopass", "gopass show -o {var}"),
    (
        "vault",
        "HashiCorp Vault",
        "vault kv get -field={var} secret/wayfinder",
    ),
    (
        "aws",
        "AWS Secrets Manager",
        "aws secretsmanager get-secret-value --secret-id {var} --query SecretString --output text",
    ),
    ("bw", "Bitwarden", "bw get password {var}"),
    ("doppler", "Doppler", "doppler secrets get {var} --plain"),
    (
        "gcloud",
        "Google Secret Manager",
        "gcloud secrets versions access latest --secret={var}",
    ),
];

/// Example `api_key_cmd` lines for the secret tools found on `PATH`.
///
/// Lets `init` / `doctor` point at *your* password manager instead of telling everyone
/// to `export` a raw secret. Returns one ready-to-edit command per detected tool (empty
/// if none are installed). Never runs anything — pure `PATH` detection.
pub fn suggest_key_commands(env_var: &str) -> Vec<String> {
    suggest_key_commands_with(env_var, which_on_path)
}

fn suggest_key_commands_with(env_var: &str, which: impl Fn(&str) -> bool) -> Vec<String> {
    KEY_HELPERS
        .iter()
        .filter(|(exe, _label, _template)| which(exe))
        .map(|(_exe, _label, template)| template.replace("{var}", env_var))
        .collect()
}

/// Whether `exe` is found as a file on any `PATH` entry.
fn which_on_path(exe: &str) -> bool {
    let Some(path) = std::env::var_os("PATH") else {
        return false;
    };
    std::env::split_paths(&path).any(|dir| dir.join(exe).is_file())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn model(base_url: &str, model: &str, api_key_env: Option<&str>) -> GatewayModel {
        GatewayModel {
            base_url: base_url.to_string(),
            model: model.to_string(),
            api_key_env: api_key_env.map(str::to_string),
            api_key_cmd: None,
            cost_per_1k: None,
            fallbacks: Vec::new(),
            context_window: None,
        }
    }

    #[test]
    fn hybrid_preset_renders_expected_structure() {
        let preset = &PRESETS["hybrid"];
        assert_eq!(preset.env_vars, &["ANTHROPIC_API_KEY"]);

        let toml = render_config(preset);
        // Key structure: a keyless local arm and an Anthropic cloud arm under a threshold.
        assert!(toml.contains("[routing]"));
        assert!(toml.contains("threshold = 0.08"));
        assert!(toml.contains("[gateway.models.local]"));
        assert!(toml.contains("[gateway.models.cloud]"));
        assert!(toml.contains("api_key_env = \"ANTHROPIC_API_KEY\""));

        // The scaffold must be valid TOML that round-trips to the documented shape.
        let parsed: toml::Value = toml.parse().expect("preset config is valid TOML");
        let cloud = &parsed["gateway"]["models"]["cloud"];
        assert_eq!(cloud["api_key_env"].as_str(), Some("ANTHROPIC_API_KEY"));
        assert_eq!(cloud["model"].as_str(), Some("claude-sonnet-4-6"));
    }

    #[test]
    fn render_env_example_lists_names_only() {
        let env = render_env_example(&PRESETS["hybrid"]);
        assert!(env.contains("ANTHROPIC_API_KEY="));
        // Names only — never a value after the `=`.
        assert!(env.ends_with("ANTHROPIC_API_KEY=\n"));
    }

    #[test]
    fn key_status_reports_set_and_unset() {
        // A unique var name keeps this test from racing other env-touching tests.
        const VAR: &str = "WAYFINDER_BOOTSTRAP_TEST_KEY";
        let mut models = BTreeMap::new();
        models.insert(
            "local".to_string(),
            model("http://localhost:11434/v1", "llama3.1", None),
        );
        models.insert(
            "cloud".to_string(),
            model(
                "https://api.anthropic.com/v1",
                "claude-sonnet-4-6",
                Some(VAR),
            ),
        );

        // SAFETY: edition 2021; a uniquely-named var read only by this test.
        std::env::set_var(VAR, "secret-value");
        let statuses = key_status(&models);
        let by_name: BTreeMap<_, _> = statuses
            .iter()
            .map(|status| (status.name.as_str(), status))
            .collect();

        let local = by_name["local"];
        assert_eq!(local.env_var, None);
        assert!(local.ok, "keyless arm is always ready");

        let cloud = by_name["cloud"];
        assert_eq!(cloud.env_var.as_deref(), Some(VAR));
        assert!(cloud.ok, "named var is set");
        assert!(missing_keys(&statuses).is_empty());

        std::env::remove_var(VAR);
        let statuses = key_status(&models);
        let cloud = statuses
            .iter()
            .find(|status| status.name == "cloud")
            .unwrap();
        assert!(!cloud.ok, "named var is unset");
        assert_eq!(missing_keys(&statuses), vec![VAR.to_string()]);
    }

    #[test]
    fn suggest_key_commands_templates_detected_tools() {
        // Detect only `op` and `pass`; assert the variable is substituted in.
        let detected = ["op", "pass"];
        let suggestions =
            suggest_key_commands_with("ANTHROPIC_API_KEY", |exe| detected.contains(&exe));
        assert_eq!(
            suggestions,
            vec![
                "op read 'op://Private/ANTHROPIC_API_KEY/credential'".to_string(),
                "pass show ANTHROPIC_API_KEY".to_string(),
            ]
        );
    }

    #[test]
    fn suggested_commands_are_valid_toml_values() {
        // Each suggestion must round-trip as a double-quoted TOML value.
        let suggestions = suggest_key_commands_with("ANTHROPIC_API_KEY", |_| true);
        assert_eq!(suggestions.len(), KEY_HELPERS.len());
        for suggestion in suggestions {
            let line = format!("api_key_cmd = \"{suggestion}\"");
            let parsed: toml::Value = line.parse().expect("suggestion is a valid TOML value");
            assert_eq!(parsed["api_key_cmd"].as_str(), Some(suggestion.as_str()));
        }
    }
}
