[package]
name = "wayfinder-internal-cli"
version = "0.0.0"
edition.workspace = true
license.workspace = true
publish.workspace = true

[lib]
name = "wayfinder_internal_cli"
path = "src/lib.rs"

[[bin]]
name = "wayfinder-router"
path = "src/main.rs"

[dependencies]
serde_json = "1"
wayfinder-internal-core = { path = "../wayfinder-core" }
wayfinder-internal-gateway = { path = "../wayfinder-gateway" }
wayfinder-internal-tui = { path = "../wayfinder-tui" }
